import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileLock2, LockKeyhole, MessageCircleMore, ShieldCheck, UsersRound } from "lucide-react";
import { Logo } from "@/components/ui/logo";

export default function Home() {
  return <><header className="landing-nav"><Logo/><nav aria-label="Navigasi publik"><a href="#cara-kerja">Cara kerja</a><a href="#privasi">Privasi</a><Link className="button button-primary button-small" href="/sign-up">Buat akun</Link></nav><Link className="mobile-auth-link" href="/sign-up">Daftar <ArrowRight size={16}/></Link></header><main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/>Satu ruang privat untuk keluarga</div><h1>Semua kebutuhan keluarga, tertata dalam satu tempat.</h1><p>Atur jadwal, bagi tugas, bagikan catatan, dan simpan dokumen penting bersama tanpa mencari ulang informasi di banyak percakapan atau platform.</p><div className="hero-actions"><Link className="button button-primary" href="/sign-up">Mulai sekarang <ArrowRight size={18}/></Link><a className="button button-secondary" href="#cara-kerja">Pelajari cara kerjanya</a></div><div className="trust-line"><ShieldCheck size={19}/><span>Buat ruang privat untuk koordinasi keluarga Anda.</span></div></div><div className="hero-visual" aria-label="Pratinjau dashboard CareCircle"><div className="mock-top"><div><span className="mock-logo"><UsersRound size={18}/></span><strong>Keluarga Harmoni</strong></div><span className="avatar">N</span></div><div className="mock-greeting"><small>Senin, 14 September</small><h2>Selamat pagi, Naya</h2><p>Apa yang perlu disiapkan hari ini?</p></div><div className="mock-agenda"><div className="agenda-date"><span>SEP</span><strong>14</strong></div><div><small>AGENDA BERIKUTNYA · 09.00</small><h3>Kontrol rutin</h3><p>Klinik Sehat Sentosa · Dimas</p></div></div><div className="mock-tasks"><div><strong>Perlu perhatian</strong><span>2 tugas</span></div><p><span className="fake-check"/>Bawa hasil sebelumnya <small>Ibu Rina</small></p><p><span className="fake-check done"><CheckCircle2 size={14}/></span>Konfirmasi transportasi <small>Dimas</small></p></div></div>
    </section>
    <section className="problem" id="cara-kerja"><div><div className="eyebrow">Mengapa CareCircle</div><h2>Informasi dan dokumen penting seharusnya tidak tercecer di banyak tempat.</h2></div><p>Ketika jadwal, tanggung jawab, catatan, dan dokumen tersebar di chat, galeri, penyimpanan pribadi, serta ingatan masing-masing, keluarga harus menyusun ulang semuanya setiap hari. CareCircle menyatukannya dalam satu Care Circle privat.</p></section>
    <section className="benefits" aria-label="Manfaat CareCircle"><article><span className="feature-icon"><ClipboardCheck/></span><h3>Tanggung jawab yang jelas</h3><p>Setiap tugas menunjukkan siapa yang menangani dan kapan perlu selesai.</p></article><article><span className="feature-icon warm"><MessageCircleMore/></span><h3>Persiapan lebih terarah</h3><p>Satukan agenda dan daftar persiapan agar tidak ada yang perlu ditebak.</p></article><article><span className="feature-icon"><FileLock2/></span><h3>Dokumen tersimpan bersama</h3><p>Simpan, lihat, dan unduh dokumen penting melalui penyimpanan privat yang hanya dapat diakses anggota.</p></article></section>
    <section className="privacy-section" id="privasi"><div className="privacy-art"><span><LockKeyhole/></span><span><UsersRound/></span><span><ShieldCheck/></span></div><div><div className="eyebrow">Privat dan terkendali</div><h2>Informasi keluarga tersedia untuk orang yang tepat.</h2><p>Tugas, jadwal, catatan, anggota, dan dokumen disatukan dalam ruang privat. Dokumen diakses melalui tautan sementara setelah sesi dan keanggotaan diperiksa.</p><ul><li><CheckCircle2/>Akses dibatasi untuk anggota Care Circle</li><li><CheckCircle2/>Dokumen disimpan pada penyimpanan privat</li><li><CheckCircle2/>CareCircle tidak memberikan diagnosis atau saran medis</li></ul></div></section>
    <section className="final-cta"><span className="feature-icon"><UsersRound/></span><h2>Merawat bersama, lebih terarah.</h2><p>Lihat bagaimana satu ruang yang tenang dapat membuat rencana keluarga lebih mudah dipahami.</p><Link className="button button-primary" href="/sign-up">Buat akun gratis <ArrowRight size={18}/></Link></section>
  </main><footer><Logo/><p>Ruang privat untuk koordinasi dan informasi keluarga.</p><div><Link href="/sign-in">Masuk</Link><Link href="/sign-up">Buat akun</Link></div><small>© 2026 CareCircle</small></footer></>;
}
